### PR TITLE
beamer template, slide titles

### PR DESCRIPTION
**Pull request by tkphd**

### CODE REVIEW

**Review by reid-a — APPROVED** [review]
Looks good. That spell-check failure will need to be fixed at some point.

**Comment by tkphd** [comment]
Ha! Got it. GitHub Actions were using a hard-coded check instead of the Makefile. Fixt.

**Comment by reid-a** [comment]
It looks like there was some re-indenting of the CLI stuff, besides the obvious/correct change to the `codespell` change?

**Comment by reid-a** [comment]
OK, got it, there were two `codespell` invocations, a live one in `test_and_build.yml` which shadowed the one in the Makefile. Good catch.

**Pull request merged**
